CREATE DATABASE BIBLIOTECA
GO
USE BIBLIOTECA
GO
CREATE TABLE LIBROS (
    ISBN        CHAR(13),
    titulo      VARCHAR(100) NOT NULL,
    precio      DECIMAL (7,2) NOT NULL

    CONSTRAINT PK_LIBROS PRIMARY KEY (ISBN)
)

CREATE TABLE SOCIOS (
    DNI         CHAR(10),
    nombre      VARCHAR(100) NOT NULL,
    ciudad      VARCHAR(100) NOT NULL

    CONSTRAINT PK_SOCIOS PRIMARY KEY (DNI)
)

CREATE TABLE PRESTAMOS (
    idPrestamo      INT IDENTITY,
    fechaPrestamo   DATE NOT NULL,
    fechaDevol      DATE,
    ISBN            CHAR(13) NOT NULL,
    DNI             CHAR(10) NOT NULL
    

    CONSTRAINT PK_PRESTAMOS PRIMARY KEY (idPrestamo),
    CONSTRAINT FK_PRESTAMOS_LIBROS FOREIGN KEY (ISBN) REFERENCES LIBROS(ISBN),
    CONSTRAINT FK_PRESTAMOS_SOCIOS FOREIGN KEY (DNI) REFERENCES SOCIOS(DNI)
)

GO

CREATE TABLE LIBROS_PERDIDOS (
    ISBN        CHAR(13),
    DNI         CHAR(10),
    nombre      VARCHAR(100),
    fechaBaja   DATE

    CONSTRAINT PK_LIBROS_PERDIDOS PRIMARY KEY (ISBN, DNI)
)

CREATE OR ALTER TRIGGER




