/*
CREATE DATABASE SUPPLIERS
GO

USE SUPPLIERS


CREATE TABLE SUPPLIERS (
	codSupplier INT IDENTITY,
	name		VARCHAR(200) NOT NULL,
	adress		VARCHAR(300) NOT NULL,

	CONSTRAINT PK_SUPPLIERS PRIMARY KEY (codSupplier)
)

CREATE TABLE PRODUCTS (
	codProduct		INT IDENTITY,
	description		VARCHAR(100) DEFAULT 'Sin descripción',
	price			DECIMAL(9,2) NOT NULL,
	stock			DECIMAL(4,0) DEFAULT 0,

	CONSTRAINT PK_PRODUCTS PRIMARY KEY (codProduct)
)


CREATE TABLE SUPPLIES (
	codSupplier INT,
	codProduct INT,
	dateSupply SMALLDATETIME,
	quantity DECIMAL(4,0),

	CONSTRAINT PK_SUPPLIES PRIMARY KEY (codSupplier, codProduct, dateSupply),
	CONSTRAINT FK_SUPPLIES_SUPPLIER FOREIGN KEY (codSupplier) REFERENCES SUPPLIERS(codSupplier),
	CONSTRAINT FK_SUPPLIES_PRODUCTS FOREIGN KEY (codProduct) REFERENCES PRODUCTS(codProduct),
)
*/
/*			ACTIVIDAD 1			*/

/*
CREATE DATABASE ACTIVITY1
GO

USE ACTIVITY1


CREATE TABLE GALLERIES (
	codGallery		INT IDENTITY,
	name			VARCHAR(200) NOT NULL,
	city			VARCHAR(150) NOT NULL,
	adress			VARCHAR(150) NOT NULL,
	squaredMeters	DECIMAL(5,2),

	CONSTRAINT PK_GALLERIES PRIMARY KEY (codGallery)
)


CREATE TABLE SCHOOLS  (
	codSchool		INT IDENTITY,
	name			VARCHAR(250) NOT NULL,
	country			VARCHAR(200) NOT NULL,

	CONSTRAINT PK_SCHOOLS PRIMARY KEY (codSchool)
)

CREATE TABLE SPONSORS (
	codSponsor		INT IDENTITY,
	name			VARCHAR(250) NOT NULL,
	country			VARCHAR(200),
	
	CONSTRAINT PK_SPONSORS PRIMARY KEY (codSponsor)

)

CREATE TABLE PAINTERS (
	codPainter			INT IDENTITY,
	name				VARCHAR(250) NOT NULL,
	country				VARCHAR(200),
	codPainterMaster	INT,
	codSchool			INT,

	CONSTRAINT PK_PAINTERS PRIMARY KEY (codPainter),
	CONSTRAINT FK_PAINTERS_PAINTERS FOREIGN KEY (codPainterMaster) REFERENCES PAINTERS(codPainter),
	CONSTRAINT FK_PAINTERS_SCHOOLS FOREIGN KEY (codSchool) REFERENCES SCHOOLS(codSchool),
)

CREATE TABLE PICTURES (
	codPicture	INT IDENTITY,
	dimensions	DECIMAL(5,2) NOT NULL,
	technique	VARCHAR(200),
	codGallery	INT,
	codPainter	INT NOT NULL,
	paintedDate	DATE,

	CONSTRAINT PK_PICTURES PRIMARY KEY (codPicture),
	CONSTRAINT PK_PICTURES_GALLERIES FOREIGN KEY (codGallery) REFERENCES GALLERIES(codGallery),
	CONSTRAINT PK_PICTURES_PAINTERS FOREIGN KEY (codPainter) REFERENCES PAINTERS(codPainter),
)

CREATE TABLE PAINTER_SPONSOR (
	codPainter			INT,
	codSponsor			INT,

	CONSTRAINT PK_PAINTER_SPONSOR PRIMARY KEY (codPainter, codSponsor),
	CONSTRAINT FK_PAINTER_SPONSOR_PAINTERS FOREIGN KEY (codPainter) REFERENCES PAINTERS(codPainter),
	CONSTRAINT FK_PAINTER_SPONSOR_SPONSORS FOREIGN KEY (codSponsor) REFERENCES SPONSORS(codSponsor),
)
*/
/*			ACTIVIDAD 2				*/
/*
CREATE DATABASE ACTIVITY2
GO

USE ACTIVITY2
*/

CREATE TABLE PROVINCIA (
	codProv			INT,
	nombre			VARCHAR(200),

	CONSTRAINT PK_PROVINCIA PRIMARY KEY (codProv),
)

CREATE TABLE MUNICIPIO (
	


)
