/*
DECLARE @NUM1 int
SET  @NUM1=200
DECLARE @NUM2 int
SET  @NUM2=150
*/

/* Exercise 1 */
DECLARE @NUM1 int
SET  @NUM1=-19
SELECT ABS(@NUM1)

/* Exercise 2 */

SELECT RAND()

/* EXERCISE 3 */
DECLARE @NUM1 int
SET  @NUM1=200
DECLARE @NUM2 int
SET  @NUM2=150
SELECT @NUM1 % @NUM2;


/* EXERCISE 4 */
DECLARE @NUM1 int
SET  @NUM1=5
DECLARE @NUM2 int
SET  @NUM2=3
SELECT POWER(@NUM1,@NUM2)

/* EXERCISE 5 */
DECLARE @NUM1 int
SET  @NUM1=5
SELECT SQRT(@NUM1)

/* EXERCISE 6 */
DECLARE @NUM1 int
SET  @NUM1=5
DECLARE @NUM2 int
SET  @NUM2=5
SELECT SQRT(POWER(@NUM1, @NUM2))

/* EXERCISE 7 */
DECLARE @RANDOMNUM FLOAT
SET @RANDOMNUM=RAND()
SELECT @RANDOMNUM

/* EXERCISE 8 */
DECLARE @RANDOMNUM INT
SET @RANDOMNUM=FLOOR(RAND()* 10 + ROUND(RAND(),0) )
SELECT @RANDOMNUM

/* EXERCISE 9 */
DECLARE @RANDOMNUM INT
SET @RANDOMNUM=FLOOR(RAND()* 100 + ROUND(RAND(),0)) 
SELECT @RANDOMNUM

/* EXERCISE 10 */
DECLARE @NUM1 FLOAT
SET @NUM1=45.267
SELECT ROUND(@NUM1, 1)

/* EXERCISE 11 */
DECLARE @NUM1 FLOAT
SET @NUM1=-0
SELECT SIGN(@NUM1)

/* EXERCISE 12 */
SELECT CONCAT('JUAN',' ', 'GARCIA',' ', 'LOPEZ')

/* EXERCISE 13 */
SELECT UPPER(CONCAT('juan',' ', 'garcia',' ', 'lopez'))

/* EXERCISE 14 */
SELECT LOWER(CONCAT('JUAN',' ', 'GARCIA',' ', 'LOPEZ'))

/* EXERCISE 15 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1=LOWER(CONCAT('JUAN',' ', 'GARCIA',' ', 'LOPEZ'))
SELECT LEFT(@NAME1, 4)

/* EXERCISE 16 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1=LOWER(CONCAT('JUAN',' ', 'GARCIA',' ', 'LOPEZ'))
SELECT RIGHT(@NAME1, 5)

/* EXERCISE 17 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1=LOWER(CONCAT('JUAN',' ', 'GARCIA',' ', 'LOPEZ'))
SELECT SUBSTRING(@NAME1, 6, 6)

/* EXERCISE 18 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1=LOWER('  JUAN GARCIA LOPEZ  ')
SELECT LEN(@NAME1)

/* EXERCISE 19 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1='SQL Tutorial'
SELECT REPLACE(@NAME1, 'SQL', 'HTML')

/* EXERCISE 20 */
DECLARE @NAME1 VARCHAR(100)
SET @NAME1='SQL Tutorial'
SELECT REVERSE(@NAME1)


/* EXERCISE 21 */
SELECT GETDATE()

/* EXERCISE 22 */
DECLARE @DATE1 DATE
SET @DATE1='03-05-2023'
SELECT DATEADD(DAY,10,@DATE1)

/* EXERCISE 23 */
/* EXERCISE 24 */
/* EXERCISE 25 */
/* EXERCISE 26 */
/* EXERCISE 27 */
