/*
CREATE DATABASE FIRSTDB

USE LIBRARY



CREATE DATABASE FIRSTDB

USE FIRSTDB
*/

CREATE TABLE SOCIOS (
	codSocio	INT IDENTITY (1,1),
	nombre		VARCHAR(50) NOT NULL,
	apellido1	VARCHAR(100) NOT NULL,
	apellido2	VARCHAR(100),
	telMovil	CHAR(9),

	CONSTRAINT PK_SOCIOS PRIMARY KEY (codSocio)
)

-- QUITAR UNA RESTRICCIÓN

ALTER TABLE SOCIOS
DROP CONSTRAINT PK_SOCIOS

-- AÑADIR UNA RESTRICCIÓN
ALTER TABLE SOCIOS
ADD CONSTRAINT PK_SOCIOS PRIMARY KEY (codSocio)