/*
CREATE DATABASE SUPPLIERS
GO

USE SUPPLIERS


CREATE TABLE SUPPLIERS (
	codSupplier INT IDENTITY,
	name		VARCHAR(200) NOT NULL,
	adress		VARCHAR(300) NOT NULL,

	CONSTRAINT PK_SUPPLIERS PRIMARY KEY (codSupplier)
)

CREATE TABLE PRODUCTS (
	codProduct		INT IDENTITY,
	description		VARCHAR(100) DEFAULT 'Sin descripcion',
	price			DECIMAL(9,2) NOT NULL,
	stock			DECIMAL(4,0) DEFAULT 0,

	CONSTRAINT PK_PRODUCTS PRIMARY KEY (codProduct)
)


CREATE TABLE SUPPLIES (
	codSupplier INT,
	codProduct INT,
	dateSupply SMALLDATETIME,
	quantity DECIMAL(4,0),

	CONSTRAINT PK_SUPPLIES PRIMARY KEY (codSupplier, codProduct, dateSupply),
	CONSTRAINT FK_SUPPLIES_SUPPLIER FOREIGN KEY (codSupplier) REFERENCES SUPPLIERS(codSupplier),
	CONSTRAINT FK_SUPPLIES_PRODUCTS FOREIGN KEY (codProduct) REFERENCES PRODUCTS(codProduct),
)
*/
/*			ACTIVIDAD 1			*/

/*
CREATE DATABASE ACTIVITY1
GO

USE ACTIVITY1


CREATE TABLE GALLERIES (
	codGallery		INT IDENTITY,
	name			VARCHAR(200) NOT NULL,
	city			VARCHAR(150) NOT NULL,
	adress			VARCHAR(150) NOT NULL,
	squaredMeters	DECIMAL(5,2),

	CONSTRAINT PK_GALLERIES PRIMARY KEY (codGallery)
)


CREATE TABLE SCHOOLS  (
	codSchool		INT IDENTITY,
	name			VARCHAR(250) NOT NULL,
	country			VARCHAR(200) NOT NULL,

	CONSTRAINT PK_SCHOOLS PRIMARY KEY (codSchool)
)

CREATE TABLE SPONSORS (
	codSponsor		INT IDENTITY,
	name			VARCHAR(250) NOT NULL,
	country			VARCHAR(200),
	
	CONSTRAINT PK_SPONSORS PRIMARY KEY (codSponsor)

)

CREATE TABLE PAINTERS (
	codPainter			INT IDENTITY,
	name				VARCHAR(250) NOT NULL,
	country				VARCHAR(200),
	codPainterMaster	INT,
	codSchool			INT,

	CONSTRAINT PK_PAINTERS PRIMARY KEY (codPainter),
	CONSTRAINT FK_PAINTERS_PAINTERS FOREIGN KEY (codPainterMaster) REFERENCES PAINTERS(codPainter),
	CONSTRAINT FK_PAINTERS_SCHOOLS FOREIGN KEY (codSchool) REFERENCES SCHOOLS(codSchool),
)

CREATE TABLE PICTURES (
	codPicture	INT IDENTITY,
	dimensions	DECIMAL(5,2) NOT NULL,
	technique	VARCHAR(200),
	codGallery	INT,
	codPainter	INT NOT NULL,
	paintedDate	DATE,

	CONSTRAINT PK_PICTURES PRIMARY KEY (codPicture),
	CONSTRAINT PK_PICTURES_GALLERIES FOREIGN KEY (codGallery) REFERENCES GALLERIES(codGallery),
	CONSTRAINT PK_PICTURES_PAINTERS FOREIGN KEY (codPainter) REFERENCES PAINTERS(codPainter),
)

CREATE TABLE PAINTER_SPONSOR (
	codPainter			INT,
	codSponsor			INT,

	CONSTRAINT PK_PAINTER_SPONSOR PRIMARY KEY (codPainter, codSponsor),
	CONSTRAINT FK_PAINTER_SPONSOR_PAINTERS FOREIGN KEY (codPainter) REFERENCES PAINTERS(codPainter),
	CONSTRAINT FK_PAINTER_SPONSOR_SPONSORS FOREIGN KEY (codSponsor) REFERENCES SPONSORS(codSponsor),
)
*/
/*			ACTIVIDAD 2				*/

/*
CREATE DATABASE ACTIVITY2
GO

USE ACTIVITY2
*/

CREATE TABLE PROVINCIA (
	codProv		INT IDENTITY,
	nombre		VARCHAR(200),

	CONSTRAINT PK_PROVINCIA PRIMARY KEY(codProv), 
)

CREATE TABLE MUNICIPIO (
	codProv		INT,
	codMuni		INT IDENTITY,
	nombre		VARCHAR(200),

	CONSTRAINT PK_MUNICIPIO PRIMARY KEY (codProv, codMuni),
	CONSTRAINT FK_MUNICIPIO_PROVINCIA FOREIGN KEY (codProv) REFERENCES PROVINCIA (codProv),
)

CREATE TABLE IMPUESTO (
	codImpuesto		INT IDENTITY,
	importe			DECIMAL (10,2),
	fechaMaxPago	DATE,
	anyo			CHAR(4),
	codMuni			INT,
	codProv			INT,

	CONSTRAINT PK_IMPUESTO PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IMPUESTO_MUNICIPIO FOREIGN KEY (codMuni, codProv) REFERENCES MUNICIPIO (codMuni, codProv),

)

CREATE TABLE IBI (
	codImpuesto		INT,
	valCastastral	DECIMAL(15,2),
	tipoImpuesto	DECIMAL(2,0),

	CONSTRAINT PK_IBI PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IBI_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto),

)

CREATE TABLE IVTM (
	codImpuesto				INT,
	tipoVehiculo			DECIMAL(2,0),
	caballosFiscales		DECIMAL(4,0),

	CONSTRAINT PK_IVTM PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IVTM_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto),

)

CREATE TABLE IAE (
	codImpuesto			INT,
	factMediaAnual		DECIMAL(12,2)

	CONSTRAINT PK_IAE PRIMARY KEY (codImpuesto),
	CONSTRAINT FK_IAE_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto),

)

CREATE TABLE OFICINA (
	codOficina		INT IDENTITY,
	nombre			VARCHAR(200),
	direccion		VARCHAR(500),

	CONSTRAINT PK_OFICINA PRIMARY KEY (codOficina),
)

CREATE TABLE CONTRIBUYENTE (
	NIF				CHAR(10),
	nombre			VARCHAR(200) NOT NULL,
	apellido1		VARCHAR(100) NOT NULL,
	apellido2		VARCHAR(100),
	direccion		VARCHAR(500),
	codPostal		CHAR(5),

	CONSTRAINT PK_CONTRIBUYENTE PRIMARY KEY (NIF),
	)

CREATE TABLE MODOS_PAGO (
	modoPago	CHAR,
	nombre		VARCHAR(200),
	activa_SN	BIT,

	CONSTRAINT PK_MODOS_PAGO PRIMARY KEY (modoPago),
)

CREATE TABLE PAGOS (
	idPago			INT IDENTITY,
	NIF				CHAR(10) NOT NULL,
	codOficina		INT NOT NULL,
	codImpuesto		INT NOT NULL,
	fechaHora		DATE NOT NULL,
	modoPago		CHAR NOT NULL,

	CONSTRAINT PK_PAGOS PRIMARY KEY (idPago),
	CONSTRAINT FK_PAGOS_CONTRIBUYENTE FOREIGN KEY (NIF) REFERENCES CONTRIBUYENTE (NIF),
	CONSTRAINT FK_PAGOS_OFICINA FOREIGN KEY (codOficina) REFERENCES OFICINA (codOficina),
	CONSTRAINT FK_PAGOS_IMPUESTO FOREIGN KEY (codImpuesto) REFERENCES IMPUESTO (codImpuesto),
	CONSTRAINT FK_PAGOS_MODOS_PAGO FOREIGN KEY (modoPago) REFERENCES MODOS_PAGO (modoPago),
)

/*	ACTIVIDAD 3		*/
/*
CREATE DATABASE ACTIVITY3
GO

USE ACTIVITY3
*/
/*
CREATE TABLE CATEGORIES (
	codCategory		INT IDENTITY,
	name			VARCHAR(200) NOT NULL,
	VAT				DECIMAL (4,2) NOT NULL,

	CONSTRAINT PK_CATEGORIES PRIMARY KEY (codCategory),

)

CREATE TABLE CLIENTS (
	codClient		INT IDENTITY, 
	name			VARCHAR(200) NOT NULL,
	adress			VARCHAR(200) NOT NULL,
	phone			CHAR(13)

	CONSTRAINT PK_CLIENTS PRIMARY KEY (codClient),


)

CREATE TABLE INDIVIDUALS (
	codClient		INT,
	DNI				CHAR(9) NOT NULL,

	CONSTRAINT PK_INDIVIDUALS PRIMARY KEY (codClient),
	CONSTRAINT FK_INDIVIDUALS_CLIENTS FOREIGN KEY (codClient) REFERENCES CLIENTS (codClient),
)

CREATE TABLE AGENCIES (
	codClient		INT,
	nameAgency		VARCHAR(200) NOT NULL,

	CONSTRAINT PK_AGENCIES PRIMARY KEY (codClient),
	CONSTRAINT FK_AGENCIES_CLIENTS FOREIGN KEY (codClient) REFERENCES CLIENTS (codClient),
)

CREATE TABLE HOTELS (
	codHotel		INT IDENTITY,
	name			VARCHAR(300) NOT NULL,
	adress			VARCHAR(500) NOT NULL,
	phone			CHAR(13) NOT NULL,
	codCategory		INT,

	CONSTRAINT PK_HOTELS PRIMARY KEY (codHotel),
	CONSTRAINT FK_HOTELS_CATEGORY FOREIGN KEY (codCategory) REFERENCES CATEGORIES (codCategory),
)

CREATE TABLE ROOMS (
	 codHotel		INT,
	 codRoom		INT IDENTITY,
	 typeRoom		INT,
	 price			DECIMAL(6,2),

	 CONSTRAINT PK_ROOMS PRIMARY KEY (codHotel, CodRoom),
	 CONSTRAINT FK_ROOMS_HOTELS FOREIGN KEY (codHotel) REFERENCES HOTELS (codHotel),
)



CREATE TABLE BOOKINGS (
	codBooking		INT IDENTITY,
	codHotel		INT	NOT NULL,
	codRoom			INT NOT NULL,
	codClient		INT NOT NULL,
	dateStart		SMALLDATETIME NOT NULL,
	dateEnd			SMALLDATETIME,
	totalPrice		DECIMAL(6,2) NOT NULL,

	CONSTRAINT PK_BOOKINGS PRIMARY KEY (codBooking),
	CONSTRAINT FK_BOOKINGS_ROOMS FOREIGN KEY (codHotel, codRoom) REFERENCES ROOMS (codHotel, codRoom),
	CONSTRAINT FK_BOOKINGS_CLIENTS FOREIGN KEY (codClient) REFERENCES CLIENTS (codClient),
)
*/
